return {
  --   'yetone/avante.nvim',
  --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --   build = vim.fn.has 'win32' ~= 0
  --           and 'powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false'
  --       or 'make',
  --   event = 'VeryLazy',
  --   version = false, -- Never set this value to "*"! Never!
  --   ---@module 'avante'
  --   ---@type avante.Config
  --   opts = {
  --       -- add any opts here
  --       -- this file can contain specific instructions for your project
  --       instructions_file = 'avante.md',
  --       mode = 'agentic',
  --       provider = "claude",
  --       providers = {
  --           claude = {
  --               endpoint = 'https://api.anthropic.com',
  --               model = 'claude-sonnet-4-20250514',
  --               timeout = 30000, -- Timeout in milliseconds
  --               extra_request_body = {
  --                   temperature = 0.75,
  --                   max_tokens = 20480,
  --               },
  --           },
  --           -- ["claude_haiku3"] = {
  --           --     endpoint = 'https://api.anthropic.com',
  --           --     model = 'claude-3-haiku-20240307',
  --           --     timeout = 20000,
  --           --     extra_request_body = {
  --           --         temperature = 0.7,
  --           --         max_tokens = 4096,
  --           --     },
  --           -- },
		-- 	-- gemini = {
  --           -- 	-- define API key via `export AVANTE_GEMINI_API_KEY=your-api-key`
  --           -- 	endpoint = 'https://generativelanguage.googleapis.com/v1beta/models',
  --           -- 	model = 'gemini-2.0-flash',
  --           -- 	timeout = 30000, -- Timeout in milliseconds
  --           -- 	context_window = 1048576,
  --           -- 	use_ReAct_prompt = true,
  --           -- 	extra_request_body = {
  --           -- 		generationConfig = {
  --           -- 			temperature = 0.75,
  --           -- 		},
  --           -- 	},
  --           -- },
  --       },
  --       behaviour = {
  --           auto_suggestions = false,
  --           auto_apply_diff_after_generation = true,
  --           auto_approve_tool_permissions = false,
  --           jump_result_buffer_on_finish = true,
  --       },
  --       selection = {
  --           enable = true,
  --           hint_display = 'delayed',
  --       },
		-- input = {
		-- 	provider = "snacks",
		-- 	provider_opts = {
		-- 		-- Additional snacks.input options
		-- 		title = "Avante Input",
		-- 		icon = " ",
		-- 	},
		-- },
  --       selector = {
		-- 	-- fzf_lua/fzf does not seem to work
  --           provider = 'native',
  --       },
  --       windows = {
  --           width = 35,
  --       },
  --   },
  --   dependencies = {
  --       'nvim-lua/plenary.nvim',
  --       'MunifTanjim/nui.nvim',
  --       --- The below dependencies are optional,
  --       'nvim-mini/mini.pick', -- for file_selector provider mini.pick
  --       'hrsh7th/nvim-cmp', -- autocompletion for avante commands and mentions
  --       'ibhagwan/fzf-lua', -- for file_selector provider fzf
  --       'stevearc/dressing.nvim', -- for input provider dressing
  --       'folke/snacks.nvim', -- for input provider snacks
  --       'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
  --       {
  --           -- support for image pasting
  --           'HakonHarnes/img-clip.nvim',
  --           event = 'VeryLazy',
  --           opts = {
  --               -- recommended settings
  --               default = {
  --                   embed_image_as_base64 = false,
  --                   prompt_for_file_name = false,
  --                   drag_and_drop = {
  --                       insert_mode = true,
  --                   },
  --                   -- required for Windows users
  --                   use_absolute_path = true,
  --               },
  --           },
  --       },
  --       {
  --           -- Make sure to set this up properly if you have lazy=true
  --           'MeanderingProgrammer/render-markdown.nvim',
  --           opts = {
  --               file_types = { 'markdown', 'Avante' },
  --           },
  --           ft = { 'markdown', 'Avante' },
  --       },
  --   },
}
